apiVersion: v1
kind: Service
metadata:
  name: megazone-backend
spec:
  selector:
    app: megazone-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: NodePort
